### ISSUE TITLE
Create package.json

### ISSUE THREAD

**Issue by KristjanESPERANTO** [gertperdZA/MMM-AfvalWijzer#2]
I am working on a new module list, which you can see [here](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/). If you search for your module in it, you will see that it looks a bit bland at the moment, as a screenshot and tags are missing.

You can change that by adding a `package.json` file and uploading the screenshot directly into the repository. The information that is currently used from the package.json is the license information (the screenshot can only be displayed if the license is free) and the keywords (these are then displayed as tags).

[Here is an example of a package.json](https://github.com/Jacopo1891/MMM-RandomQuotes/blob/master/package.json).

It would be nice if you would add one to your repository :slightly_smiling_face:

**Comment by gertperdZA** [comment]
I have added the package.json, a screenshot, and a LICENCE file :) Please let me know if that is sufficient.

**Comment by KristjanESPERANTO** [comment]
Thanks! Your module now looks nice on the new list :rocket: :smiley:  I've just opened a PR (#4) for other details :slightly_smiling_face:
